debian/tmp/usr/lib/python2.7/dist-packages/shinken/webui                                       /usr/lib/python2.7/dist-packages/shinken/

debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/active_directory_ui.py              /usr/lib/python2.7/dist-packages/shinken/modules/
debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/passwd_ui.py                        /usr/lib/python2.7/dist-packages/shinken/modules/
debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/graphite_ui.py                      /usr/lib/python2.7/dist-packages/shinken/modules/
debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/openldap_ui.py                      /usr/lib/python2.7/dist-packages/shinken/modules/
debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/pnp_ui.py                           /usr/lib/python2.7/dist-packages/shinken/modules/
debian/tmp/usr/lib/python2.7/dist-packages/shinken/modules/sqlite_generic.py                   /usr/lib/python2.7/dist-packages/shinken/modules/
